

services:
  postgres:
    image: postgres:15-alpine
    container_name: rust-backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: verceldb
      POSTGRES_USER: default
      POSTGRES_PASSWORD: zLfXyUm6g5Ax
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .\\scripts\\sql:/scripts/sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U default -d verceldb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: